set_property SRC_FILE_INFO {cfile:E:/digital_logic/Top_Piano/Top_Piano.srcs/constrs_1/new/ego1_pins.xdc rfile:../../../Top_Piano.srcs/constrs_1/new/ego1_pins.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports clk]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K5  IOSTANDARD LVCMOS33} [get_ports ps2_clk]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L4  IOSTANDARD LVCMOS33} [get_ports ps2_data]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T1  IOSTANDARD LVCMOS33} [get_ports audio_pwm]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M6  IOSTANDARD LVCMOS33} [get_ports audio_sd]
